package com.teampurado.view;

import com.teampurado.model.classes.Student;
import com.teampurado.model.classes.Teacher;
import com.teampurado.model.database.DBHelper;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author DarkHeavens
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        DBHelper db = new DBHelper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnMode = new javax.swing.ButtonGroup();
        pnLogin = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        lbPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        rbtnTeacher = new javax.swing.JRadioButton();
        rbtnStudent = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnLogin.setBackground(new java.awt.Color(51, 51, 51));

        lbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teampurado/imgs/guest-xxl.png"))); // NOI18N

        tfUser.setBackground(new java.awt.Color(102, 102, 102));
        tfUser.setForeground(new java.awt.Color(204, 204, 204));

        pfPass.setBackground(new java.awt.Color(102, 102, 102));
        pfPass.setForeground(new java.awt.Color(204, 204, 204));

        lbPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teampurado/imgs/13-512.png"))); // NOI18N

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("GosmickSans", 0, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        rbtnTeacher.setBackground(new java.awt.Color(51, 51, 51));
        gbtnMode.add(rbtnTeacher);
        rbtnTeacher.setForeground(new java.awt.Color(153, 153, 153));
        rbtnTeacher.setText("TEACHER");
        rbtnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTeacherActionPerformed(evt);
            }
        });

        rbtnStudent.setBackground(new java.awt.Color(51, 51, 51));
        gbtnMode.add(rbtnStudent);
        rbtnStudent.setForeground(new java.awt.Color(153, 153, 153));
        rbtnStudent.setText("STUDENT");

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbtnTeacher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(rbtnStudent)
                        .addGap(21, 21, 21))
                    .addComponent(pfPass)
                    .addComponent(tfUser)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTeacher)
                    .addComponent(rbtnStudent))
                .addGap(7, 7, 7)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTeacherActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        DBHelper db = new DBHelper();
        Connection conn = db.getConn();
        String id = "";
        String name = "";
        String pass = "";
        
        try {
            if(rbtnTeacher.isSelected()){
                sql = "select * from teacher where binary id = '"+tfUser.getText()+"' and binary password = '"+pfPass.getText()+"'";
            } else{
                sql = "select * from student where binary id = '"+tfUser.getText()+"' and binary password = '"+pfPass.getText()+"'";
            }

            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            System.out.println(""+sql);
            if(rs.next()){
                id = rs.getString("id");
                name = rs.getString("name");
                pass = rs.getString("password");
                
                System.out.println(""+id+" "+name+" "+pass);
                if(rbtnTeacher.isSelected()){
                    Teacher t = new Teacher(id,name,pass);
                    TeacherFrame tf = new TeacherFrame();
                    tf.setVisible(true);
                }else{
                    Student s = new Student(id,name,pass);
                    StudentFrame sf = new StudentFrame(id,name,pass);
                    sf.setVisible(true);
                } this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "ID or Passwsord is incorrect.", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
            
            
//            while(rs.next()){
//                String id = rs.getString("id");
//                String name = rs.getString("name");
//                String pass = rs.getString("password");
//                
//                Teacher t = new Teacher(id,name,pass);
//                
//            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup gbtnMode;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JRadioButton rbtnStudent;
    private javax.swing.JRadioButton rbtnTeacher;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
    private Statement stmt=null;
    private String sql;
    private ResultSet rs=null;
    
}
